apiVersion: v1
kind: ConfigMap
metadata:
  name: jjb-config
  namespace: jenkins-project-neha
data:
  jenkins_jobs.ini: |
    [job_builder]
    ignore_cache=True
    keep_descriptions=False
    include_path=.:scripts:~/git/
    recursive=False
    exclude=.*:manual:./development
    allow_duplicates=False
    update=all

    [jenkins]
    user=admin
    password=admin123
    url=http://10.0.212.146:32099
    query_plugins_info=False
